name: Build DITA Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Nightly build at 2am UTC

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DITA_ENGINE_REPO: https://github.com/Xelophon26/DITA_Engine.git
      DITA_ENGINE_DIR: dita-ot
      DITAMAP_FILE: Drill_3000/Cordlessdrill_3000/binding/Cordless_3000_Manual.ditamap
      OUTPUT_FORMAT: pdf
      OUTPUT_DIR: output

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Clone DITA-OT
        run: |
          git clone $DITA_ENGINE_REPO $DITA_ENGINE_DIR
          chmod +x $DITA_ENGINE_DIR/bin/dita

      - name: Build PDF
        run: |
          export DITA_HOME=$(pwd)/$DITA_ENGINE_DIR
          $DITA_HOME/bin/dita --input=$DITAMAP_FILE --format=$OUTPUT_FORMAT --output=$OUTPUT_DIR

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: DITA PDF output
          path: ${{ env.OUTPUT_DIR }}
